CREATE SEQUENCE CUSTOMERS_SEQ START WITH 1 INCREMENT BY 50;

CREATE TABLE CUSTOMERS (
    ID NUMBER DEFAULT CUSTOMERS_SEQ.NEXTVAL NOT NULL,
    NAME VARCHAR2(255 CHAR) NOT NULL,
    EMAIL VARCHAR2(255 CHAR) NOT NULL
);

INSERT INTO CUSTOMERS(
    NAME,
    EMAIL
) VALUES (
    'john',
    'john@mail.com'
);